from pre_defined_answers import all_projects, all_certifications, all_qualifications, all_experience
all_project_questions = [
"Can you list his Projects?",
"list his Projects?",
"his Projects?",
"Projects?",
"His Projects?",
"Can you list Vijayram's Projects?",
"Can you list Vijay's Projects?",
"Vijayram's Projects?",
"Vijay's Projects?",
"What projects has Vijay worked on?",
"What projects has Vijayram worked on?",
"What projects has he worked on?",
"Vijay worked on which projects?",
"Vijayram worked on which projects?",
"He worked on which projects?",
"Which projects has Vijay worked on?",
"Which projects has Vijayram worked on?",
"Which projects has he worked on?",
"Tell me about Vijayram's projects",
"Tell me about Vijay's projects",
"Tell me about his projects",
"What are some of Vijayram's past projects?",
"What are some of Vijay's past projects?",
"What are some of his past projects?",
"List all projects Vijayram has worked on",
"List all projects VIjay has worked on",
"List all projects he has worked on",
"Can you provide details on Vijayram's projects?",
"Can you provide details on Vijay's projects?",
"Can you provide details on his projects?",
"Can you provide details on projects?",
"provide details on projects?",
"Give me an overview of Vijay's projects",
"Give me an overview of Vijayram's projects",
"Give me an overview of his projects",
"What kind of projects has Vijay worked on?",
"What kind of projects has Vijayram worked on?",
"What kind of projects has he worked on?",
"Can you summarize Vijayram's project experience?",
"Can you summarize Vijay's project experience?",
"Can you summarize his project experience?",
"What are Vijayram's key projects?",
"What are Vijay's key projects?",
"What are his key projects?",
"Has Vijay worked on any notable projects?",
"Has Vijayram worked on any notable projects?",
"Has he worked on any notable projects?",
"Show me Vijayram's project portfolio",
"Show me Vijay's project portfolio",
"Show me his project portfolio.",
"What projects are in Vijay's portfolio?",
"What projects are in Vijayram's portfolio?",
"What projects are in his portfolio?",
"Provide a list of Vijayram's completed projects",
"Provide a list of Vijay's completed projects",
"Provide a list of his completed projects",
"list of Vijayram's completed projects",
"list of Vijay's completed projects",
"list of his completed projects",
"tell me about your projects",
"tell me about projects",
"projects you have worked in",
"give me a list of projects you have worked on",
"can you tell me about any projects you have worked on?",
"can you tell me about any Vijayram's project?",
"can you tell me about any Vijay's project?",
"can you tell me about his projects?",
"tell me about any projects you have worked on?",
"what are some of your projects?",
]

all_certification_questions = [
    "Can you list his certifications?",
    "List his certifications?",
    "His certifications?",
    "Certifications?",
    "His Certifications?",
    "Can you list Vijayram's certifications?",
    "Can you list Vijay's certifications?",
    "Vijayram's certifications?",
    "Vijay's certifications?",
    "What certifications does Vijay have?",
    "What certifications does Vijayram have?",
    "What certifications does he have?",
    "Vijay holds which certifications?",
    "Vijayram holds which certifications?",
    "He holds which certifications?",
    "Which certifications has Vijay earned?",
    "Which certifications has Vijayram earned?",
    "Which certifications has he earned?",
    "Tell me about Vijayram's certifications",
    "Tell me about Vijay's certifications",
    "Tell me about his certifications",
    "What are some of Vijayram's professional certifications?",
    "What are some of Vijay's professional certifications?",
    "What are some of his professional certifications?",
    "List all certifications Vijayram has obtained",
    "List all certifications Vijay has obtained",
    "List all certifications he has obtained",
    "Can you provide details on Vijayram's certifications?",
    "Can you provide details on Vijay's certifications?",
    "Can you provide details on his certifications?",
    "Provide details on certifications?",
    "Give me an overview of Vijay's certifications",
    "Give me an overview of Vijayram's certifications",
    "Give me an overview of his certifications",
    "What type of certifications does Vijay hold?",
    "What type of certifications does Vijayram hold?",
    "What type of certifications does he hold?",
    "Can you summarize Vijayram's certification history?",
    "Can you summarize Vijay's certification history?",
    "Can you summarize his certification history?",
    "What are Vijayram's key certifications?",
    "What are Vijay's key certifications?",
    "What are his key certifications?",
    "Has Vijay earned any notable certifications?",
    "Has Vijayram earned any notable certifications?",
    "Has he earned any notable certifications?",
    "Show me Vijayram's certification portfolio",
    "Show me Vijay's certification portfolio",
    "Show me his certification portfolio",
    "What certifications are in Vijay's credentials?",
    "What certifications are in Vijayram's credentials?",
    "What certifications are in his credentials?",
    "Provide a list of Vijayram's professional certifications",
    "Provide a list of Vijay's professional certifications",
    "Provide a list of his professional certifications",
    "List of Vijayram's completed certifications",
    "List of Vijay's completed certifications",
    "List of his completed certifications",
    "Tell me about your certifications",
    "Tell me about professional certifications",
    "Certifications you have earned",
    "Give me a list of certifications you have obtained",
    "Can you tell me about any certifications you've earned?",
    "Can you tell me about Vijayram's certification achievements?",
    "Can you tell me about Vijay's certification achievements?",
    "Can you tell me about his certification achievements?",
    "What are some of your certifications?",
    "Does Vijay have any Scrum certifications?",
    "Has Vijayram completed any machine learning certifications?",
    "What technology certifications does he possess?",
    "When did Vijay obtain his Salesforce certification?",
    "Which institutions issued Vijayram's certifications?",
    "Are Vijay's certifications still valid?",
    "How many certifications does he currently hold?",
    "What's the most recent certification Vijay earned?",
    "Has Vijayram renewed any expired certifications?",
    "Did Vijay receive any certification honors or distinctions?",
    "certificstions?",  # Intentional typo coverage
    "certificstions list?",
    "his certificstions?",
    "wat r his certs?",  # Text-speak variation
    "vijay's certs?",
    "certs list?"
]

all_qualification_questions = [
    "Can you list his qualifications?",
    "List his qualifications?",
    "His qualifications?",
    "Qualifications?",
    "His Qualifications?",
    "Can you list Vijayram's qualifications?",
    "Can you list Vijay's qualifications?",
    "Vijayram's qualifications?",
    "Vijay's qualifications?",
    "What qualifications does Vijay have?",
    "What qualifications does Vijayram have?",
    "What qualifications does he have?",
    "Vijay holds which qualifications?",
    "Vijayram holds which qualifications?",
    "He holds which qualifications?",
    "Which qualifications has Vijay obtained?",
    "Which qualifications has Vijayram obtained?",
    "Which qualifications has he obtained?",
    "Tell me about Vijayram's educational background",
    "Tell me about Vijay's academic qualifications",
    "Tell me about his professional qualifications",
    "What are Vijayram's academic credentials?",
    "What are Vijay's educational qualifications?",
    "What are his professional credentials?",
    "List all degrees Vijayram has earned",
    "List all certifications Vijay has completed",
    "List all professional qualifications he possesses",
    "Can you provide details on Vijayram's educational history?",
    "Can you provide details on Vijay's academic background?",
    "Can you provide details on his professional training?",
    "Provide details on qualifications?",
    "Give me an overview of Vijay's education",
    "Give me an overview of Vijayram's credentials",
    "Give me an overview of his academic history",
    "What type of degrees does Vijay hold?",
    "What type of certifications does Vijayram possess?",
    "What kind of professional training has he completed?",
    "Can you summarize Vijayram's educational journey?",
    "Can you summarize Vijay's career qualifications?",
    "Can you summarize his academic achievements?",
    "What are Vijayram's key credentials?",
    "What are Vijay's main qualifications?",
    "What are his primary certifications?",
    "Has Vijay earned any advanced degrees?",
    "Has Vijayram completed any specialized training?",
    "Has he obtained any professional licenses?",
    "Show me Vijayram's academic portfolio",
    "Show me Vijay's professional credentials",
    "Show me his educational certificates",
    "What qualifications are listed in Vijay's CV?",
    "What credentials are in Vijayram's resume?",
    "What academic achievements are in his profile?",
    "Provide a list of Vijayram's academic qualifications",
    "Provide a list of Vijay's professional certifications",
    "Provide a list of his completed trainings",
    "List of Vijayram's educational milestones",
    "List of Vijay's career certifications",
    "List of his professional accomplishments",
    "Tell me about your educational background",
    "Tell me about professional qualifications",
    "Degrees you have earned",
    "Give me a list of credentials you possess",
    "Can you tell me about any advanced degrees you've earned?",
    "Can you tell me about Vijayram's academic honors?",
    "Can you tell me about Vijay's professional licenses?",
    "Can you tell me about his technical certifications?",
    "What are some of your academic achievements?",
    "Does Vijay have any engineering degrees?",
    "Has Vijayram completed any MBA program?",
    "What technical qualifications does he possess?",
    "When did Vijay obtain his bachelor's degree?",
    "Which universities did Vijayram attend?",
    "Are Vijay's certifications internationally recognized?",
    "How many professional qualifications does he currently hold?",
    "What's the highest qualification Vijay has achieved?",
    "Has Vijayram pursued any doctoral studies?",
    "Did Vijay receive any academic awards?",
    "qualifciation?",  # Common misspelling
    "qualifcation list?",  # Typo variation
    "his qualifcation?",  # Spelling error
    "wat r his quals?",  # Text-speak variation
    "vijay's edu background?",
    "academic creds?",
    "list ur qualifications?",  # Informal phrasing
    "what skools did he go to?",  # Intentional misspelling
    "any degrees?",  # Ultra-short form
    "he got phd?",  # Colloquial phrasing
    "vijayram graduted from where?",
    "his collage details?"  # Common misspelling
]

all_experience_questions = [
    # Work Experience Variations
    "What is Vijay's Work Experience?",
    "What is Vijayram's Work Experience?",
    "What is his Work Experience?",
    "Work Experience?",
    "VIjay's Work Expeirence?",
    "Vijayram's Work Expeirence?",
    "his Work Expeirence?",
    "Can you list Vijay's Work Experience?",
    "Can you list Vijayram's Work Experience?",
    "Can you list his Work Experience?",
    "Describe Vijay's Work Experience",
    "Describe Vijayram's Work Experience",
    "Describe his Work Experience",
    "How much Work Experience does Vijay have?",
    "How much Work Experience does Vijayram have?",
    "How much Work Experience does he have?",
    "Detail Vijay's Work Experience",
    "Detail Vijayram's Work Experience",
    "Detail his Work Experience",
    "Tell me about Vijay's Work Experience",
    "Tell me about Vijayram's Work Experience",
    "Tell me about his Work Experience",
    "What are the highlights of Vijay's Work Experience?",
    "What are the highlights of Vijayram's Work Experience?",
    "What are the highlights of his Work Experience?",
    "How long has Vijay been working?",
    "How long has Vijayram been working?",
    "How long has he been working?",
    
    # Professional Experience Variations
    "What is Vijay's Professional Experience?",
    "What is Vijayram's Professional Experience?",
    "What is his Professional Experience?",
    "Professional Experience?",
    "VIjay's Professional Expeirence?",
    "Vijayram's Professional Expeirence?",
    "his Professional Expeirence?",
    "Could you outline Vijay's Professional Experience?",
    "Could you outline Vijayram's Professional Experience?",
    "Could you outline his Professional Experience?",
    "Summarize Vijay's Professional Experience",
    "Summarize Vijayram's Professional Experience",
    "Summarize his Professional Experience",
    "What roles has Vijay held in his Professional Experience?",
    "What roles has Vijayram held in his Professional Experience?",
    "What roles has he held in his Professional Experience?",
    "Explain Vijay's Professional Background",
    "Explain Vijayram's Professional Background",
    "Explain his Professional Background",
    
    # Industry Experience Variations
    "What is Vijay's Industry Experience?",
    "What is Vijayram's Industry Experience?",
    "What is his Industry Experience?",
    "Industry Experience?",
    "VIjay's Industry Expeirence?",
    "Vijayram's Industry Expeirence?",
    "his Industry Expeirence?",
    "Which industries has Vijay worked in?",
    "Which industries has Vijayram worked in?",
    "Which industries has he worked in?",
    "What sectors does Vijay have experience in?",
    "What sectors does Vijayram have experience in?",
    "What sectors does he have experience in?",
    "Describe Vijay's Industry Background",
    "Describe Vijayram's Industry Background",
    "Describe his Industry Background",
    
    # Work History/Background Variations
    "What is Vijay's Work History?",
    "What is Vijayram's Work History?",
    "What is his Work History?",
    "Work History?",
    "VIjay's Work History?",
    "Vijayram's Work History?",
    "his Work History?",
    "What companies has Vijay worked for?",
    "What companies has Vijayram worked for?",
    "What companies has he worked for?",
    "Where has Vijay worked before?",
    "Where has Vijayram worked before?",
    "Where has he worked before?",
    "What is Vijay's Employment History?",
    "What is Vijayram's Employment History?",
    "What is his Employment History?",
    
    # Career Experience & Skills
    "What is Vijay's Career Experience?",
    "What is Vijayram's Career Experience?",
    "What is his Career Experience?",
    "Career Experience?",
    "What skills has Vijay gained from his experience?",
    "What skills has Vijayram gained from his experience?",
    "What skills has he gained from his experience?",
    "What are Vijay's key career achievements?",
    "What are Vijayram's key career achievements?",
    "What are his key career achievements?",
    "What responsibilities has Vijay handled?",
    "What responsibilities has Vijayram handled?",
    "What responsibilities has he handled?",
    
    # Duration & Progression
    "How many years of experience does Vijay have?",
    "How many years of experience does Vijayram have?",
    "How many years of experience does he have?",
    "How did Vijay start his career?",
    "How did Vijayram start his career?",
    "How did he start his career?",
    "What is Vijay's career progression?",
    "What is Vijayram's career progression?",
    "What is his career progression?",
    
    # Informal/Alternative Phrasings
    "Tell me about Vijay's work background",
    "Tell me about Vijayram's work background",
    "Tell me about his work background",
    "What's Vijay's work story?",
    "What's Vijayram's work story?",
    "What's his work story?",
    "Got any details on Vijay's experience?",
    "Got any details on Vijayram's experience?",
    "Got any details on his experience?",
    "Walk me through Vijay's career",
    "Walk me through Vijayram's career",
    "Walk me through his career",
    "What does Vijay do professionally?",
    "What does Vijayram do professionally?",
    "What does he do professionally?",
]



dict = {}


for i in all_project_questions:
    dict[i] = all_projects

for i in all_certification_questions:
    dict[i] = all_certifications

for i in all_qualification_questions:
    dict[i] = all_qualifications

for i in all_experience_questions:
    dict[i] = all_experience

with open("stored_questions.py", "w") as file:
    file.write(f"var = {str(dict)}")