[theme]
primaryColor = "#800020"            # burgundy
backgroundColor = "#161A1D"         # soft charcoal (was #0B0C10)
secondaryBackgroundColor = "#24282B"  # muted slate gray (was #1C1C1C)
textColor = "#E0DCC8"               # soft beige
font = "serif"